# Generated by Django 4.2.16 on 2024-10-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtlantaFoodFinder', '0002_favorite'),
        ('AtlantaFoodFinder', '0002_restaurant_review'),
    ]

    operations = [
    ]
