# Generated by Django 4.2.16 on 2024-10-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtlantaFoodFinder', '0004_remove_restaurant_description_restaurant_cuisine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='hashed_address',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
